package atividade1;

public class Computador {
    private integer memoriamRAM; 4096
    private Integer SSD: 
    private Integer nucleos;
    private Double


    public integer getMemoriamRAM() {
        return this.memoriamRAM;
    }

    public void setMemoriamRAM(integer memoriamRAM) {
        this.memoriamRAM = memoriamRAM;
    }

    public Integer getNucleos() {
        return this.nucleos;
    }

    public void setNucleos(Integer nucleos) {
        this.nucleos = nucleos;
    }


}

