package atividade1;

public class Main {
    public static void main(String[] args) {
        Computador pc = new Computador(memoriaRAM: 4096, SSD 256, nucleos: 4, OperacoesPorsegundo 15.0);   
        Programa p1 = new Computador(memoriaRAM: 2048, SSD 512, nucleos: 5000, quantidadedeOperacoes 15.0);
        Programa p2 = new Computador(memoriaRAM: 4096*2, SSDocupado 128, nucleos: 5000, quantidadedeOperacoes 15.0); 
        Programa p3 = new Computador(memoriaRAM: 2048, SSD 128, nucleos: 5000, quantidadedeOperacoes 15.0)
          }
}