package atividade1;

public class Programa{
    private integer memoriamRAMAlocada; 
    private Integer SSDOcupado: 
    private Integer quantidadedeoperacoes;
    private Double

    public Programa() {

    public integer getMemoriamRAMAlocada() {
        return this.memoriamRAMAlocada;
    }

    public void setMemoriamRAMAlocada(integer memoriamRAMAlocada) {
        this.memoriamRAMAlocada = memoriamRAMAlocada;
    }

    public Integer getQuantidadedeoperacoes() {
        return this.quantidadedeoperacoes;
    }

    public void setQuantidadedeoperacoes(Integer quantidadedeoperacoes) {
        this.quantidadedeoperacoes = quantidadedeoperacoes;
    }
    }


}
